### ISSUE TITLE
Unhandled exception when increasing sample number

### ISSUE THREAD

**Issue by flxkrmr** [JonathanTaquet/Oe2sSLE#14]
I get an exception (and application shutdown) when I increase a very low number of a sample to a number that is already taken by another sample. I tried that with the very first samples (e.g. #19 or #20). This is what the console prints.

```
/usr/lib/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "Oe2sSLE_GUI.py", line 494, in _varString_set
    self.SNScommand()
  File "Oe2sSLE_GUI.py", line 1347, in _oscNum_command
    samples[lN+1].oscNum.set(samples[lN].oscNum.get()+1 if samples[lN].oscNum.get() != 421 else 501)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 266, in set
    return self._tk.globalsetvar(self._name, value)
_tkinter.TclError: can't set "PY_VAR33": can't set "PY_VAR40": can't set "PY_VAR43": can't set "PY_VAR50": can't set "PY_VAR53": can't set "PY_VAR60": can't set "PY_VAR63": can't set "PY_VAR70": can't set "PY_VAR73": can't set "PY_VAR80": can't set "PY_VAR83": can't set "PY_VAR90": can't set "PY_VAR93": can't set "PY_VAR100": can't set "PY_VAR103": can't set "PY_VAR110": can't set "PY_VAR113": can't set "PY_VAR120": can't set "PY_VAR123": can't set "PY_VAR130": can't set "PY_VAR133": can't set "PY_VAR140": can't set "PY_VAR143": can't set "PY_VAR150": can't set "PY_VAR153": can't set "PY_VAR160": can't set "PY_VAR163": can't set "PY_VAR170": can't set "PY_VAR173": can't set "PY_VAR180": can't set "PY_VAR183": can't set "PY_VAR190": can't set "PY_VAR193": can't set "PY_VAR200": can't set "PY_VAR203": can't set "PY_VAR210": can't set "PY_VAR213": can't set "PY_VAR220": can't set "PY_VAR223": can't set "PY_VAR230": can't set "PY_VAR233": can't set "PY_VAR240": can't set "PY_VAR243": can't set "PY_VAR250": can't set "PY_VAR253": can't set "PY_VAR260": can't set "PY_VAR263": can't set "PY_VAR270": can't set "PY_VAR273": can't set "PY_VAR280": can't set "PY_VAR283": can't set "PY_VAR290": can't set "PY_VAR293": can't set "PY_VAR300": can't set "PY_VAR303": can't set "PY_VAR310": can't set "PY_VAR313": can't set "PY_VAR320": can't set "PY_VAR323": can't set "PY_VAR330": can't set "PY_VAR333": can't set "PY_VAR340": can't set "PY_VAR343": can't set "PY_VAR350": can't set "PY_VAR353": can't set "PY_VAR360": can't set "PY_VAR363": can't set "PY_VAR370": can't set "PY_VAR373": can't set "PY_VAR380": can't set "PY_VAR383": can't set "PY_VAR390": can't set "PY_VAR393": can't set "PY_VAR400": can't set "PY_VAR403": can't set "PY_VAR410": can't set "PY_VAR413": can't set "PY_VAR420": can't set "PY_VAR423": can't set "PY_VAR430": can't set "PY_VAR433": can't set "PY_VAR440": can't set "PY_VAR443": can't set "PY_VAR450": can't set "PY_VAR453": can't set "PY_VAR460": can't set "PY_VAR463": can't set "PY_VAR470": can't set "PY_VAR473": can't set "PY_VAR480": can't set "PY_VAR483": can't set "PY_VAR490": can't set "PY_VAR493": can't set "PY_VAR500": can't set "PY_VAR503": can't set "PY_VAR510": can't set "PY_VAR513": can't set "PY_VAR520": can't set "PY_VAR523": can't set "PY_VAR530": can't set "PY_VAR533": can't set "PY_VAR540": can't set "PY_VAR543": can't set "PY_VAR550": can't set "PY_VAR553": can't set "PY_VAR560": can't set "PY_VAR563": can't set "PY_VAR570": can't set "PY_VAR573": can't set "PY_VAR580": can't set "PY_VAR583": can't set "PY_VAR590": can't set "PY_VAR593": can't set "PY_VAR600": can't set "PY_VAR603": can't set "PY_VAR610": can't set "PY_VAR613": can't set "PY_VAR620": can't set "PY_VAR623": can't set "PY_VAR630": can't set "PY_VAR633": can't set "PY_VAR640": can't set "PY_VAR643": can't set "PY_VAR650": can't set "PY_VAR653": can't set "PY_VAR660": can't set "PY_VAR663": can't set "PY_VAR670": can't set "PY_VAR673": can't set "PY_VAR680": can't set "PY_VAR683": can't set "PY_VAR690": can't set "PY_VAR693": can't set "PY_VAR700": can't set "PY_VAR703": can't set "PY_VAR710": can't set "PY_VAR713": can't set "PY_VAR720": can't set "PY_VAR723": can't set "PY_VAR730": can't set "PY_VAR733": can't set "PY_VAR740": can't set "PY_VAR743": can't set "PY_VAR750": can't set "PY_VAR753": can't set "PY_VAR760": can't set "PY_VAR763": can't set "PY_VAR770": can't set "PY_VAR773": can't set "PY_VAR780": can't set "PY_VAR783": can't set "PY_VAR790": 97.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Oe2sSLE_GUI.py", line 2009, in <module>
    app.mainloop()
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1123, in mainloop
    self.tk.mainloop(n)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1540, in __call__
    self.widget._report_exception()
AttributeError: 'StringVar' object has no attribute '_report_exception'
```

I saw that you use some kind of logging, but unfortunately I cannot find any log file. Do I have to enable it somewhere?
BTW later I realized that the expected behaviour is to increase all other samples too. A very handy feature! :+1:

**Comment by JonathanTaquet** [comment]
I'm sorry, but I could not reproduce this issue. Could you give me more details on how it occurs? What did you do before? can you reproduce it?

When something is logged, there should be an Oe2sSLE.log file created on your working directory.
