### ISSUE TITLE
Crash on window scroll

### ISSUE THREAD

**Issue by baneizalfe** [JonathanTaquet/Oe2sSLE#24]
When I load samples and try to scroll through them program crashes with this error:
`Traceback (most recent call last):
  File "Oe2sSLE_GUI.py", line 2350, in <module>
    app.mainloop()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
`

Environment: macOS Sierra

Steps to reproduce:
1. Start program (using python 3) 
2. Load samples (at least 20)
3. Try to scroll through
4. Program crashes with above traceback

**Comment by JonathanTaquet** [comment]
Are you using the release version?
If not, look at Issue #20: there is a tk/tkinter problem with python for mac, look at the python web site, it explains how to properly install python and a correct version of tcl/tk.
